Repository bascht/omemo-top, pull requests merged in 2020-05, with the labels that each got.

#192 fix tracking_issue url
  _data/clients/kaidan.yml
Labels: waiting for feedback

#197 Add snikket client
  _data/clients/snikket.yml
Labels: Status update

#202 fix #184: make status text more clear
  _includes/client_row.html
Labels: enhancement
